"use client";
import { useState } from "react";
import { Leaf } from "lucide-react";
import Comprar from "../mercado/PagoModal";
import { PLANTAS, LIM_DIA, POR_KILO, TRAF } from "@/lib/cultivo";
const $ = (n) => `$${Number(n || 0).toLocaleString("es")}`;
const call = async (b) => { const r = await fetch("/api/cultivo", { method: "POST", body: JSON.stringify(b) }), j = await r.json().catch(() => ({})); if (!r.ok) { alert(j.error || "Error"); return null; } return j; };
function Stack({ s }) {
  const [unidad, setU] = useState("bolsa"), [cant, setC] = useState(""), [of, setOf] = useState(null), [q, setQ] = useState(""), [res, setRes] = useState([]), [to, setTo] = useState(null), [n, setN] = useState(""), [precio, setP] = useState("");
  const kilos = Math.floor(s.cant / POR_KILO);
  return (<div className="card" style={{ marginTop: 8 }}><div style={{ display: "flex", gap: 10, alignItems: "center" }}>{s.img && <img src={s.img} alt="" style={{ width: 70, height: 46, objectFit: "cover", borderRadius: 8 }} />}<div><b>{s.name}</b><div className="mut">{s.cant} bolsitas · {kilos} kilo(s) completos ({POR_KILO} bolsitas = 1 kilo)</div></div></div>
    <div style={{ marginTop: 10 }}><b>Vender al traficante</b><div className="mut" style={{ fontSize: 12 }}>Base: {$(TRAF.bolsa)} por bolsita o {$(TRAF.kilo)} por kilo. Es un mercado fluctuante: la oferta puede ser mucho menor o mucho mayor y dura {TRAF.minutos} minutos. Tú decides si aceptas.</div>
      <div className="row2"><select value={unidad} onChange={(e) => setU(e.target.value)}><option value="bolsa">Bolsitas</option><option value="kilo">Kilos</option></select><input type="number" min="1" value={cant} onChange={(e) => setC(e.target.value)} placeholder="Cantidad" /><button className="btn g" onClick={async () => { const j = await call({ accion: "oferta", name: s.name, at: s.at, unidad, cant }); if (j) setOf(j.oferta); }}>Pedir oferta</button></div>
      {of && <div className="card" style={{ padding: 10, marginTop: 6, borderColor: of.total >= of.base ? "var(--ok)" : "var(--bad)" }}>El traficante ofrece <b style={{ fontSize: 20 }}>{$(of.total)}</b> por {of.n} {of.unidad === "kilo" ? "kilo(s)" : "bolsita(s)"} <span className="mut">({of.pct}% del precio base de {$(of.base)})</span>
        <div style={{ display: "flex", gap: 8, marginTop: 6 }}><button className="btn" onClick={async () => { const j = await call({ accion: "aceptarOferta" }); if (j) { alert(j.msg); location.reload(); } }}>Aceptar</button><button className="btn g" onClick={async () => { await call({ accion: "rechazarOferta" }); setOf(null); }}>Rechazar</button></div></div>}</div>
    <div style={{ marginTop: 10 }}><b>Vender a un jugador</b>
      <form className="row2" onSubmit={async (e) => { e.preventDefault(); const r = await fetch("/api/delictivo?q=" + encodeURIComponent(q)); if (r.ok) setRes((await r.json()).users); }}><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Nombre, Roblox o cédula" /><button className="btn g">Buscar</button></form>
      {res.map((x) => <div key={x.id} className="card" style={{ cursor: "pointer", padding: 8, marginTop: 4, borderColor: to?.id === x.id ? "var(--ac)" : "var(--bd)" }} onClick={() => setTo(x)}>{x.label}</div>)}
      {to && <div className="row2" style={{ marginTop: 6 }}><input type="number" min="1" max={s.cant} value={n} onChange={(e) => setN(e.target.value)} placeholder="Bolsitas" /><input type="number" min="1" value={precio} onChange={(e) => setP(e.target.value)} placeholder="Precio total acordado ($)" /><button className="btn" onClick={async () => { if (await call({ accion: "ofrecer", name: s.name, at: s.at, to: to.id, cant: n, precio })) { alert("Oferta enviada. Espera a que el comprador acepte."); location.reload(); } }}>Ofrecer a {to.label.split(" · ")[0]}</button></div>}</div></div>);
}
export default function Cultivo({ metodos, hoy, bolsas, enviadas }) {
  return (<div className="card"><b style={{ display: "flex", gap: 6, alignItems: "center" }}><Leaf size={18} />Mercado negro · Cultivo</b>
    <p className="mut">Compra semillas, siémbralas en el patio de tu casa (48 horas reales), cosecha 150 bolsitas por planta y véndelas. Guarda siempre evidencias (fotos o video) del rol de la plantación. La policía puede revisar tu casa con una orden judicial y quitarte lo que lleves encima. Máximo {LIM_DIA} semillas de cada tipo cada 24 horas.</p>
    <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(240px,1fr))", gap: 10 }}>{Object.entries(PLANTAS).map(([k, p]) => (<div key={k} className="card" style={{ margin: 0 }}><div className="mi"><img src={p.img} alt="" /></div><b>{p.semilla}</b><div className="big" style={{ fontSize: 22, color: "var(--ac)" }}>{$(p.precio)}</div><div className="mut">Hoy: {hoy[k] || 0}/{LIM_DIA} · Bolsita: {$(p.bolsa)}</div>
      <Comprar url="/api/cultivo" body={{ accion: "comprar", tipo: k }} metodos={metodos} msg="Semilla comprada. Está en tu inventario." disabled={(hoy[k] || 0) >= LIM_DIA} off="Límite diario alcanzado" /></div>))}</div>
    <h3 style={{ marginTop: 14 }}>Lo que llevas encima</h3>{bolsas.map((s) => <Stack key={s.name + s.at} s={s} />)}{!bolsas.length && <p className="mut">No llevas bolsitas encima. Cosecha tus plantas, sácalas del inventario de la casa y véndelas aquí (lo que está en casa no se puede vender).</p>}
    {enviadas.length > 0 && <><h3 style={{ marginTop: 14 }}>Ofertas enviadas</h3>{enviadas.map((o) => <div key={o.id} style={{ display: "flex", justifyContent: "space-between", gap: 8, padding: "6px 0", borderTop: "1px solid var(--bd)" }}><span>{o.n} bolsitas ({o.name}) a {o.paraN} por {$(o.precio)}</span><button className="btn g" onClick={async () => { if (await call({ accion: "cancelar", id: o.id })) location.reload(); }}>Cancelar</button></div>)}</>}</div>);
}
