name: Descomprimir

on:
  workflow_dispatch:
  push:
    paths:
      - 'verp-portal.zip'

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Descomprimir proyecto
        run: |
          unzip -o verp-portal.zip
          cp -a verp-portal/. .
          rm -rf verp-portal verp-portal.zip

      - name: Guardar cambios
        run: |
          git config user.name "bot"
          git config user.email "bot@users.noreply.github.com"
          git add -A
          git commit -m "Agregar proyecto verp-portal" || true
          git push
