name: Descomprimir VERP

on:
  workflow_dispatch:
  push:
    paths:
      - 'verp-portal.zip'

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Descomprimir ZIP
        run: |
          unzip -o verp-portal.zip -d temp_verp
          cp -a temp_verp/*/. .
          rm -rf temp_verp verp-portal.zip

      - name: Guardar cambios
        run: |
          git config user.name "bot"
          git config user.email "bot@users.noreply.github.com"
          git add -A
          git commit -m "Actualizar portal VERP" || true
          git push
