"use client";
// Panel del dueño: edita precios (e impuestos en el concesionario) y los planes de la tienda de móvil.
export default function Gestion({ k, items, planes, paga = true, estado = "normal", multaOk = false, comida = false, aviso = null }) {
  const post = async (b) => { const r = await fetch("/api/negocios", { method: "POST", body: JSON.stringify({ key: k, ...b }) }), j = await r.json().catch(() => ({})); alert(r.ok ? "Guardado" : j.error || "Error"); if (r.ok) location.reload(); };
  const cl = estado === "clausurado", mo = estado === "moroso", v = (e) => { e.preventDefault(); return Object.fromEntries(new FormData(e.target)); };
  return (<div className="card" style={{ marginTop: 10 }}><b>Administrar mi negocio</b>
    {aviso && <div className="card" style={{ margin: "8px 0", borderColor: aviso.sube ? "var(--bad)" : "var(--ok)" }}><b style={{ color: aviso.sube ? "var(--bad)" : "var(--ok)" }}>{aviso.sube ? "⬆ El Ministro del Interior SUBIÓ el ITBMS" : "⬇ El Ministro del Interior BAJÓ el ITBMS"}</b><div className="mut">De {aviso.de}% a {aviso.a}% el {new Date(aviso.at).toLocaleDateString("es")}.</div></div>}
    {mo && <div className="card" style={{ margin: "8px 0", borderColor: "var(--bad)" }}><b style={{ color: "var(--bad)" }}>NEGOCIO MOROSO</b><div className="mut">Dejaste de pagar impuestos. Para regularizarte ve a la Policía: te pondrán una multa que pagas en Inventario → Multas. Después el Ministro del Interior decide si queda limpio (pago normal) o lo clausura.</div></div>}
    {cl && <div className="card" style={{ margin: "8px 0", borderColor: "var(--bad)" }}><b style={{ color: "var(--bad)" }}>NEGOCIO CLAUSURADO</b><div className="mut">El Ministro del Interior clausuró tu negocio: no puede vender. Ve a la Policía y paga la multa de reapertura (Inventario → Multas) para reabrirlo, o déjalo.</div>
      <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 8 }}><button className="btn" disabled={!multaOk} onClick={() => post({ accion: "reabrir" })}>{multaOk ? "Reabrir negocio" : "Reabrir (falta pagar la multa)"}</button><button className="btn g" onClick={() => confirm("¿Dejar el negocio? Dejas de ser el dueño y queda a la venta.") && post({ accion: "abandonar" })}>Dejar el negocio</button></div></div>}
    {k !== "taller" && !comida && !cl && <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 8, margin: "8px 0", flexWrap: "wrap" }}><span>ITBMS: <b style={{ color: paga ? "var(--ok)" : "var(--bad)" }}>{paga ? "pagas el impuesto" : "NO pagas el impuesto"}</b><div className="mut">Cada venta lleva ITBMS. Si pagas, va a la Tesorería. Si dejas de pagar, el negocio queda MOROSO: solo la Policía y el Ministro del Interior pueden regularizarlo.</div></span>
      <button className="btn g" disabled={mo && !paga} onClick={() => post({ accion: "impuesto", paga: !paga })}>{paga ? "Dejar de pagar" : mo ? "Solo la Policía te regulariza" : "Volver a pagar"}</button></div>}
    {comida && !cl && <p className="mut">Las comidas y bebidas no llevan impuestos. El precio máximo de cada una es $500.</p>}
    {k === "movil" && <form onSubmit={(e) => { const f = v(e); post({ accion: "planes", planes: [f.a, f.b, f.c] }); }} style={{ display: "flex", gap: 6, flexWrap: "wrap", margin: "8px 0" }}><span className="mut">Planes semanales ($):</span>{["a", "b", "c"].map((n, i) => <input key={n} name={n} type="number" defaultValue={planes[i]} style={{ width: 80 }} />)}<button className="btn">Guardar planes</button></form>}
    {cl ? null : k === "taller" ? <p className="mut">Tu taller se gestiona desde la Dark Web: negocia ofertas de autos robados y revende.</p> : items.map((i) => <form key={i.id} onSubmit={(e) => { const f = v(e); post({ accion: "editar", id: i.id, price: f.price, impuesto: f.impuesto }); }} style={{ display: "flex", gap: 6, alignItems: "center", margin: "6px 0", flexWrap: "wrap" }}>
      <span style={{ flex: 1, minWidth: 140 }}>{i.name}</span><input name="price" type="number" min="0" max={comida ? 500 : undefined} defaultValue={i.price} style={{ width: 110 }} />{k === "concesionario" && <input name="impuesto" type="number" min="0" defaultValue={i.impuesto} placeholder="Impuesto" style={{ width: 100 }} />}<button className="btn g">Guardar</button></form>)}</div>);
}
